# 数据库连接
[database]
type = "mysql"
host = "119.29.117.244"
port = 3306
user = "root"
pass = "fuck123"
name = "gfast_open"
charset = "utf8mb4" #数据库编码
maxIdle = 10 #连接池最大闲置的连接数
maxOpen = 10 #连接池最大打开的连接数
maxLifetime = 30 #(单位秒)连接对象可重复使用的时间长度
debug = true
path = "data/log/sql"
level = "all"
stdout = true

#web服务器配置
[server]
name = "user"
version = "0.1.1"

# Redis数据库配置
[redis]
Address = "119.29.117.244:6379,1"

#jwt配置
[gToken]
CacheMode = 2
CacheKey = "GToken:"
Timeout = 0
MaxRefresh = 0
TokenDelimiter = "_"
EncryptKey = "koi29a83idakguqjq29asd9asd8a7jhq"
AuthFailMsg = "登录超时，请重新登录"
MultiLogin = true

[registry]
registryType = "etcd"
addrs = ["127.0.0.1:2380"]