// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pay.proto

package client

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PayStatusReq struct {
	OrderId              []int64  `protobuf:"varint,1,rep,packed,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayStatusReq) Reset()         { *m = PayStatusReq{} }
func (m *PayStatusReq) String() string { return proto.CompactTextString(m) }
func (*PayStatusReq) ProtoMessage()    {}
func (*PayStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{0}
}

func (m *PayStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayStatusReq.Unmarshal(m, b)
}
func (m *PayStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayStatusReq.Marshal(b, m, deterministic)
}
func (m *PayStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayStatusReq.Merge(m, src)
}
func (m *PayStatusReq) XXX_Size() int {
	return xxx_messageInfo_PayStatusReq.Size(m)
}
func (m *PayStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayStatusReq proto.InternalMessageInfo

func (m *PayStatusReq) GetOrderId() []int64 {
	if m != nil {
		return m.OrderId
	}
	return nil
}

type PayStatusReply struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	IsPay                []bool   `protobuf:"varint,2,rep,packed,name=is_pay,json=isPay,proto3" json:"is_pay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayStatusReply) Reset()         { *m = PayStatusReply{} }
func (m *PayStatusReply) String() string { return proto.CompactTextString(m) }
func (*PayStatusReply) ProtoMessage()    {}
func (*PayStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{1}
}

func (m *PayStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayStatusReply.Unmarshal(m, b)
}
func (m *PayStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayStatusReply.Marshal(b, m, deterministic)
}
func (m *PayStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayStatusReply.Merge(m, src)
}
func (m *PayStatusReply) XXX_Size() int {
	return xxx_messageInfo_PayStatusReply.Size(m)
}
func (m *PayStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PayStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_PayStatusReply proto.InternalMessageInfo

func (m *PayStatusReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PayStatusReply) GetIsPay() []bool {
	if m != nil {
		return m.IsPay
	}
	return nil
}

func init() {
	proto.RegisterType((*PayStatusReq)(nil), "client.PayStatusReq")
	proto.RegisterType((*PayStatusReply)(nil), "client.PayStatusReply")
}

func init() { proto.RegisterFile("pay.proto", fileDescriptor_0564d675d5c516e0) }

var fileDescriptor_0564d675d5c516e0 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x48, 0xac, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x51, 0xd2, 0xe4,
	0xe2, 0x09, 0x48, 0xac, 0x0c, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x0e, 0x4a, 0x2d, 0x14, 0x92, 0xe4,
	0xe2, 0xc8, 0x2f, 0x4a, 0x49, 0x2d, 0x8a, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd6, 0x60, 0x0e,
	0x62, 0x07, 0xf3, 0x3d, 0x53, 0x94, 0xac, 0xb9, 0xf8, 0x90, 0x94, 0x16, 0xe4, 0x54, 0x0a, 0x09,
	0x71, 0xb1, 0x24, 0xe7, 0xa7, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x42,
	0xa2, 0x5c, 0x6c, 0x99, 0xc5, 0xf1, 0x05, 0x89, 0x95, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0x1c, 0x41,
	0xac, 0x99, 0xc5, 0x01, 0x89, 0x95, 0x46, 0xae, 0x5c, 0x6c, 0x05, 0x89, 0x95, 0x8e, 0x05, 0x99,
	0x42, 0xd6, 0x5c, 0x9c, 0x70, 0x63, 0x84, 0x44, 0xf4, 0x20, 0xee, 0xd0, 0x43, 0x76, 0x84, 0x94,
	0x18, 0x16, 0xd1, 0x82, 0x9c, 0x4a, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xeb, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x65, 0xbd, 0xe7, 0xaa, 0xca, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PayApiClient is the client API for PayApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayApiClient interface {
	PayStatus(ctx context.Context, in *PayStatusReq, opts ...grpc.CallOption) (*PayStatusReply, error)
}

type payApiClient struct {
	cc *grpc.ClientConn
}

func NewPayApiClient(cc *grpc.ClientConn) PayApiClient {
	return &payApiClient{cc}
}

func (c *payApiClient) PayStatus(ctx context.Context, in *PayStatusReq, opts ...grpc.CallOption) (*PayStatusReply, error) {
	out := new(PayStatusReply)
	err := c.cc.Invoke(ctx, "/client.payApi/PayStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayApiServer is the server API for PayApi service.
type PayApiServer interface {
	PayStatus(context.Context, *PayStatusReq) (*PayStatusReply, error)
}

// UnimplementedPayApiServer can be embedded to have forward compatible implementations.
type UnimplementedPayApiServer struct {
}

func (*UnimplementedPayApiServer) PayStatus(ctx context.Context, req *PayStatusReq) (*PayStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayStatus not implemented")
}

func RegisterPayApiServer(s *grpc.Server, srv PayApiServer) {
	s.RegisterService(&_PayApi_serviceDesc, srv)
}

func _PayApi_PayStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayApiServer).PayStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.payApi/PayStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayApiServer).PayStatus(ctx, req.(*PayStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PayApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "client.payApi",
	HandlerType: (*PayApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PayStatus",
			Handler:    _PayApi_PayStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pay.proto",
}
