// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

// 服务注册名，客户端通过这个名称访问服务

package pb_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	protocol "novel/protocol"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_OK    ErrorCode = 0
	ErrorCode_Error ErrorCode = 1001
)

var ErrorCode_name = map[int32]string{
	0:    "OK",
	1001: "Error",
}

var ErrorCode_value = map[string]int32{
	"OK":    0,
	"Error": 1001,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

type SayHelloReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloReq) Reset()         { *m = SayHelloReq{} }
func (m *SayHelloReq) String() string { return proto.CompactTextString(m) }
func (*SayHelloReq) ProtoMessage()    {}
func (*SayHelloReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *SayHelloReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloReq.Unmarshal(m, b)
}
func (m *SayHelloReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloReq.Marshal(b, m, deterministic)
}
func (m *SayHelloReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloReq.Merge(m, src)
}
func (m *SayHelloReq) XXX_Size() int {
	return xxx_messageInfo_SayHelloReq.Size(m)
}
func (m *SayHelloReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloReq.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloReq proto.InternalMessageInfo

func (m *SayHelloReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SayHelloRsp struct {
	Result               *protocol.Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SayHelloRsp) Reset()         { *m = SayHelloRsp{} }
func (m *SayHelloRsp) String() string { return proto.CompactTextString(m) }
func (*SayHelloRsp) ProtoMessage()    {}
func (*SayHelloRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *SayHelloRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloRsp.Unmarshal(m, b)
}
func (m *SayHelloRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloRsp.Marshal(b, m, deterministic)
}
func (m *SayHelloRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloRsp.Merge(m, src)
}
func (m *SayHelloRsp) XXX_Size() int {
	return xxx_messageInfo_SayHelloRsp.Size(m)
}
func (m *SayHelloRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloRsp proto.InternalMessageInfo

func (m *SayHelloRsp) GetResult() *protocol.Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterEnum("net.novel.api.user.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*SayHelloReq)(nil), "net.novel.api.user.SayHelloReq")
	proto.RegisterType((*SayHelloRsp)(nil), "net.novel.api.user.SayHelloRsp")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xca, 0x4b, 0x2d, 0xd1, 0xcb, 0xcb, 0x2f, 0x4b,
	0xcd, 0xd1, 0x4b, 0x2c, 0xc8, 0xd4, 0x2b, 0x2d, 0x4e, 0x2d, 0x92, 0x92, 0x06, 0xf3, 0xf5, 0xc1,
	0x0a, 0x92, 0xf3, 0x73, 0xf4, 0x93, 0xf3, 0x73, 0x73, 0xf3, 0xf3, 0x20, 0x1a, 0x94, 0x14, 0xb9,
	0xb8, 0x83, 0x13, 0x2b, 0x3d, 0x52, 0x73, 0x72, 0xf2, 0x83, 0x52, 0x0b, 0x85, 0x84, 0xb8, 0x58,
	0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x53, 0x24,
	0x25, 0xc5, 0x05, 0x42, 0x6a, 0x5c, 0x6c, 0x45, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x60, 0x45, 0xdc,
	0x46, 0x7c, 0x7a, 0x50, 0x03, 0x83, 0xc0, 0xa2, 0x41, 0x50, 0x59, 0x2d, 0x79, 0x2e, 0x4e, 0xd7,
	0xa2, 0xa2, 0xfc, 0x22, 0xe7, 0xfc, 0x94, 0x54, 0x21, 0x36, 0x2e, 0x26, 0x7f, 0x6f, 0x01, 0x06,
	0x21, 0x2e, 0x2e, 0x56, 0xb0, 0xa0, 0xc0, 0x4b, 0x76, 0xa3, 0x68, 0x2e, 0x6e, 0x97, 0xd4, 0xdc,
	0xfc, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x1f, 0x2e, 0x0e, 0x98, 0x35, 0x42, 0xf2,
	0x7a, 0x98, 0xfe, 0xd0, 0x43, 0x72, 0xa7, 0x14, 0x7e, 0x05, 0xc5, 0x05, 0x4e, 0x9c, 0x51, 0xec,
	0x05, 0x49, 0xf1, 0x20, 0xe1, 0x24, 0x36, 0xb0, 0x4f, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x0d, 0x2b, 0x4f, 0x86, 0x28, 0x01, 0x00, 0x00,
}
