// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: demo.proto

// 服务注册名，客户端通过这个名称访问服务

package pb_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	_ "novel/protocol"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DemoService service

type DemoService interface {
	SayHello(ctx context.Context, in *SayHelloReq, opts ...client.CallOption) (*SayHelloRsp, error)
}

type demoService struct {
	c    client.Client
	name string
}

func NewDemoService(name string, c client.Client) DemoService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "net.novel.api.user"
	}
	return &demoService{
		c:    c,
		name: name,
	}
}

func (c *demoService) SayHello(ctx context.Context, in *SayHelloReq, opts ...client.CallOption) (*SayHelloRsp, error) {
	req := c.c.NewRequest(c.name, "DemoService.SayHello", in)
	out := new(SayHelloRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DemoService service

type DemoServiceHandler interface {
	SayHello(context.Context, *SayHelloReq, *SayHelloRsp) error
}

func RegisterDemoServiceHandler(s server.Server, hdlr DemoServiceHandler, opts ...server.HandlerOption) error {
	type demoService interface {
		SayHello(ctx context.Context, in *SayHelloReq, out *SayHelloRsp) error
	}
	type DemoService struct {
		demoService
	}
	h := &demoServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&DemoService{h}, opts...))
}

type demoServiceHandler struct {
	DemoServiceHandler
}

func (h *demoServiceHandler) SayHello(ctx context.Context, in *SayHelloReq, out *SayHelloRsp) error {
	return h.DemoServiceHandler.SayHello(ctx, in, out)
}
