// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 系统保留错误码 0-999
type ERet int32

const (
	ERet_kRetSuccess         ERet = 0
	ERet_kRetErrParameter    ERet = 1
	ERet_kRetErrCookie       ERet = 2
	ERet_kRetErrUnauthorized ERet = 3
	ERet_kRetErrUnknowUri    ERet = 4
	ERet_kRetErrVersion      ERet = 5
	ERet_kRetErrBusy         ERet = 6
	ERet_accessTokenExpired  ERet = 7
	ERet_refreshTokenExpired ERet = 8
	ERet_noResult            ERet = 9
	ERet_touristTokenExpired ERet = 10
	ERet_kRetErrNotLogin     ERet = 100
	ERet_kRetErrSystem       ERet = 999
)

var ERet_name = map[int32]string{
	0:   "kRetSuccess",
	1:   "kRetErrParameter",
	2:   "kRetErrCookie",
	3:   "kRetErrUnauthorized",
	4:   "kRetErrUnknowUri",
	5:   "kRetErrVersion",
	6:   "kRetErrBusy",
	7:   "accessTokenExpired",
	8:   "refreshTokenExpired",
	9:   "noResult",
	10:  "touristTokenExpired",
	100: "kRetErrNotLogin",
	999: "kRetErrSystem",
}

var ERet_value = map[string]int32{
	"kRetSuccess":         0,
	"kRetErrParameter":    1,
	"kRetErrCookie":       2,
	"kRetErrUnauthorized": 3,
	"kRetErrUnknowUri":    4,
	"kRetErrVersion":      5,
	"kRetErrBusy":         6,
	"accessTokenExpired":  7,
	"refreshTokenExpired": 8,
	"noResult":            9,
	"touristTokenExpired": 10,
	"kRetErrNotLogin":     100,
	"kRetErrSystem":       999,
}

func (x ERet) String() string {
	return proto.EnumName(ERet_name, int32(x))
}

func (ERet) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type Header_Meta int32

const (
	Header_NotUse       Header_Meta = 0
	Header_AppVersion   Header_Meta = 1024
	Header_OSType       Header_Meta = 1025
	Header_OSVersion    Header_Meta = 1026
	Header_DeviceID     Header_Meta = 1027
	Header_DeviceType   Header_Meta = 1028
	Header_Uid          Header_Meta = 1029
	Header_RoomId       Header_Meta = 1030
	Header_ClientIPPort Header_Meta = 1031
)

var Header_Meta_name = map[int32]string{
	0:    "NotUse",
	1024: "AppVersion",
	1025: "OSType",
	1026: "OSVersion",
	1027: "DeviceID",
	1028: "DeviceType",
	1029: "Uid",
	1030: "RoomId",
	1031: "ClientIPPort",
}

var Header_Meta_value = map[string]int32{
	"NotUse":       0,
	"AppVersion":   1024,
	"OSType":       1025,
	"OSVersion":    1026,
	"DeviceID":     1027,
	"DeviceType":   1028,
	"Uid":          1029,
	"RoomId":       1030,
	"ClientIPPort": 1031,
}

func (x Header_Meta) String() string {
	return proto.EnumName(Header_Meta_name, int32(x))
}

func (Header_Meta) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1, 0}
}

type Result struct {
	ErrCode              int64    `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetErrCode() int64 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *Result) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type Header struct {
	MapExtend            map[uint32]string `protobuf:"bytes,1,rep,name=map_extend,json=mapExtend,proto3" json:"map_extend" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ServiceName          string            `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name"`
	SeqId                uint64            `protobuf:"varint,3,opt,name=seq_id,json=seqId,proto3" json:"seq_id"`
	Uri                  uint32            `protobuf:"varint,4,opt,name=uri,proto3" json:"uri"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetMapExtend() map[uint32]string {
	if m != nil {
		return m.MapExtend
	}
	return nil
}

func (m *Header) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Header) GetSeqId() uint64 {
	if m != nil {
		return m.SeqId
	}
	return 0
}

func (m *Header) GetUri() uint32 {
	if m != nil {
		return m.Uri
	}
	return 0
}

// 业务主动push，通过http接口调用，roomid和uids放在url parameters
type ServerPush struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerPush) Reset()         { *m = ServerPush{} }
func (m *ServerPush) String() string { return proto.CompactTextString(m) }
func (*ServerPush) ProtoMessage()    {}
func (*ServerPush) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *ServerPush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPush.Unmarshal(m, b)
}
func (m *ServerPush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPush.Marshal(b, m, deterministic)
}
func (m *ServerPush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPush.Merge(m, src)
}
func (m *ServerPush) XXX_Size() int {
	return xxx_messageInfo_ServerPush.Size(m)
}
func (m *ServerPush) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPush.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPush proto.InternalMessageInfo

func (m *ServerPush) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ServerPush) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterEnum("common.ERet", ERet_name, ERet_value)
	proto.RegisterEnum("common.Header_Meta", Header_Meta_name, Header_Meta_value)
	proto.RegisterType((*Result)(nil), "common.Result")
	proto.RegisterType((*Header)(nil), "common.Header")
	proto.RegisterMapType((map[uint32]string)(nil), "common.Header.MapExtendEntry")
	proto.RegisterType((*ServerPush)(nil), "common.ServerPush")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x53, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xae, 0x93, 0xd4, 0xdd, 0x4c, 0x3e, 0xba, 0x9d, 0xf6, 0x7d, 0x1b, 0x90, 0x90, 0x42, 0x0e,
	0x28, 0xe2, 0xd0, 0x43, 0xb9, 0x20, 0xd4, 0x0b, 0x6d, 0x23, 0x35, 0x12, 0x6d, 0x23, 0xa7, 0xe1,
	0xc0, 0x25, 0x72, 0xe3, 0xa1, 0x59, 0xa5, 0xde, 0x75, 0x67, 0xd7, 0xa1, 0xe1, 0xc4, 0x37, 0x12,
	0x77, 0x7e, 0x1e, 0x67, 0xfe, 0x06, 0xb2, 0xe3, 0x20, 0x72, 0x9b, 0xe7, 0xc3, 0xfb, 0xec, 0x33,
	0xf2, 0x42, 0x7d, 0x62, 0xe2, 0xd8, 0xe8, 0x83, 0x84, 0x8d, 0x33, 0xe8, 0x2f, 0x51, 0xe7, 0x08,
	0xfc, 0x80, 0x6c, 0x7a, 0xeb, 0xf0, 0x01, 0x08, 0x62, 0x1e, 0x4f, 0x4c, 0x44, 0x2d, 0xaf, 0xed,
	0x75, 0xcb, 0xc1, 0x16, 0x31, 0x9f, 0x98, 0x88, 0x70, 0x1f, 0xb2, 0x71, 0x1c, 0xdb, 0x9b, 0x56,
	0xa9, 0xed, 0x75, 0xab, 0x81, 0x4f, 0xcc, 0xe7, 0xf6, 0xa6, 0xf3, 0xab, 0x04, 0xfe, 0x19, 0x85,
	0x11, 0x31, 0x1e, 0x01, 0xc4, 0x61, 0x32, 0xa6, 0x7b, 0x47, 0x3a, 0x6a, 0x79, 0xed, 0x72, 0xb7,
	0x76, 0xf8, 0xe8, 0xa0, 0xc8, 0x5c, 0x7a, 0x0e, 0xce, 0xc3, 0xa4, 0x97, 0xeb, 0x3d, 0xed, 0x78,
	0x11, 0x54, 0xe3, 0x15, 0xc6, 0xc7, 0x50, 0xb7, 0xc4, 0x73, 0x35, 0xa1, 0xb1, 0x0e, 0x63, 0x2a,
	0x62, 0x6a, 0x05, 0x77, 0x11, 0xc6, 0x84, 0xff, 0x81, 0x6f, 0xe9, 0x6e, 0xac, 0xa2, 0x56, 0xb9,
	0xed, 0x75, 0x2b, 0xc1, 0xa6, 0xa5, 0xbb, 0x7e, 0x84, 0x12, 0xca, 0x29, 0xab, 0x56, 0xa5, 0xed,
	0x75, 0x1b, 0x41, 0x36, 0x3e, 0x3c, 0x82, 0xe6, 0x7a, 0x50, 0xe6, 0x99, 0xd1, 0x22, 0x6f, 0xd5,
	0x08, 0xb2, 0x11, 0xf7, 0x60, 0x73, 0x1e, 0xde, 0xa6, 0xab, 0xa0, 0x25, 0x78, 0x51, 0x7a, 0xee,
	0x75, 0x7e, 0x78, 0x50, 0x39, 0x27, 0x17, 0x22, 0x80, 0x7f, 0x61, 0xdc, 0xc8, 0x92, 0xdc, 0xc0,
	0x6d, 0x80, 0x97, 0x49, 0xf2, 0x9a, 0xd8, 0x2a, 0xa3, 0xe5, 0x07, 0x81, 0x35, 0xf0, 0x2f, 0x87,
	0x57, 0x8b, 0x84, 0xe4, 0x47, 0x81, 0x4d, 0xa8, 0x5e, 0x0e, 0x57, 0xe2, 0x27, 0x81, 0x0d, 0x10,
	0xa7, 0x94, 0xdd, 0xbb, 0x7f, 0x2a, 0x3f, 0x8b, 0xec, 0xe3, 0x25, 0xcc, 0xfd, 0x5f, 0x04, 0x0a,
	0x28, 0x8f, 0x54, 0x24, 0xbf, 0xe6, 0xc7, 0x04, 0xc6, 0xc4, 0xfd, 0x48, 0x7e, 0x13, 0xb8, 0x03,
	0xf5, 0x93, 0x5b, 0x45, 0xda, 0xf5, 0x07, 0x03, 0xc3, 0x4e, 0x7e, 0x17, 0x9d, 0x33, 0x80, 0x21,
	0xf1, 0x9c, 0x78, 0x90, 0xda, 0x29, 0x3e, 0x01, 0x7f, 0x9a, 0x2f, 0x32, 0x6f, 0x52, 0x3b, 0x6c,
	0xae, 0xaf, 0x37, 0x28, 0x54, 0x44, 0xa8, 0x5c, 0x9b, 0x68, 0x51, 0x74, 0xcb, 0xe7, 0xa7, 0x3f,
	0x4b, 0x50, 0xe9, 0x05, 0xe4, 0x70, 0x1b, 0x6a, 0xb3, 0x80, 0xdc, 0x30, 0x9d, 0x4c, 0xc8, 0x5a,
	0xb9, 0x81, 0x7b, 0x20, 0x33, 0xa2, 0xc7, 0x3c, 0x08, 0x39, 0x8c, 0xc9, 0x11, 0x4b, 0x0f, 0x77,
	0xa0, 0x51, 0xb0, 0x27, 0xc6, 0xcc, 0x14, 0xc9, 0x12, 0xee, 0xc3, 0x6e, 0x41, 0x8d, 0x74, 0x98,
	0xba, 0xa9, 0x61, 0xf5, 0x9e, 0x22, 0x59, 0xfe, 0xe7, 0x84, 0x91, 0x9e, 0x69, 0xf3, 0x6e, 0xc4,
	0x4a, 0x56, 0x10, 0xa1, 0x59, 0xb0, 0xab, 0xd5, 0x6c, 0xae, 0xc2, 0x7b, 0xcc, 0xc7, 0xa9, 0x5d,
	0x48, 0x1f, 0xff, 0x07, 0x0c, 0xf3, 0x8b, 0x5c, 0x99, 0x19, 0xe9, 0xde, 0x7d, 0xa2, 0x98, 0x22,
	0xb9, 0x95, 0x65, 0x31, 0xbd, 0x65, 0xb2, 0xd3, 0x35, 0x41, 0x60, 0x1d, 0x84, 0x36, 0xcb, 0x3f,
	0x56, 0x56, 0x33, 0x9b, 0x33, 0x29, 0x2b, 0xeb, 0xd6, 0x6c, 0x80, 0xbb, 0xb0, 0x5d, 0x04, 0x5d,
	0x18, 0xf7, 0xca, 0xdc, 0x28, 0x2d, 0x23, 0xc4, 0xbf, 0x9d, 0x86, 0x0b, 0xeb, 0x28, 0x96, 0xbf,
	0xb7, 0x8e, 0xc5, 0x9b, 0xe2, 0x25, 0x5c, 0xfb, 0xf9, 0xc3, 0x78, 0xf6, 0x27, 0x00, 0x00, 0xff,
	0xff, 0xee, 0xa8, 0xa5, 0xe6, 0x28, 0x03, 0x00, 0x00,
}
